# Generated by Django 5.2.7 on 2026-07-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_attendancesession_reference_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesession",
            name="class_type",
            field=models.CharField(
                choices=[("online", "Online"), ("offline", "Offline")],
                default="online",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="pattern_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
