# Generated by Django 5.2.7 on 2026-08-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_attendancesession_class_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="verification_reasons",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="verification_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="board_type",
            field=models.CharField(
                choices=[
                    ("whiteboard", "Whiteboard"),
                    ("blackboard", "Blackboard"),
                    ("greenboard", "Greenboard"),
                    ("glass", "Glass Board"),
                    ("paper", "Paper"),
                ],
                default="whiteboard",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="instruction_card",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("pending_review", "Pending Review"),
                ],
                default="present",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="attendancesession",
            name="pattern_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
