# Generated by Django 5.2.7 on 2026-08-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_attendancerecord_verification_reasons_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesession",
            name="shape_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
