# Generated by Django 5.2.7 on 2026-08-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_attendancesession_shape_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancesession",
            name="board_type",
        ),
    ]
