# Generated by Django 5.2.7 on 2026-08-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_remove_attendancesession_board_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancesession",
            name="class_type",
            field=models.CharField(
                choices=[("qr", "QR"), ("pattern", "Pattern")],
                default="qr",
                max_length=10,
            ),
        ),
    ]
