# Generated by Django 5.2.7 on 2026-08-25 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_alter_attendancesession_class_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="roll_no",
        ),
        migrations.AlterField(
            model_name="attendancesession",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
