# Generated by Django 5.2.7 on 2026-09-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
