# Generated by Django 5.0.7 on 2026-08-31 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('required_attendance_pct', models.FloatField(default=75.0)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'academic_terms',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('low_verification', 'Low Verification Score'), ('burst_marking', 'Burst Marking (possible proxy cluster)'), ('session_collision', 'Session Collision (two places at once)'), ('late_outlier', 'Latency Outlier'), ('post_session_mark', 'Marked After Session End'), ('cohort_drop', 'Cohort Attendance Drop')], max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('score', models.FloatField(default=0.0)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attendance_flags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterventionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField()),
                ('baseline_pct', models.FloatField(blank=True, null=True)),
                ('baseline_sessions', models.PositiveIntegerField(default=0)),
                ('followup_pct', models.FloatField(blank=True, null=True)),
                ('followup_sessions', models.PositiveIntegerField(default=0)),
                ('delta_points', models.FloatField(blank=True, null=True)),
                ('control_delta_points', models.FloatField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('pending', 'Pending (insufficient follow-up sessions)'), ('improved', 'Improved'), ('unchanged', 'Unchanged'), ('declined', 'Declined')], default='pending', max_length=12)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'intervention_logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='expected_sessions_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='sessions_per_week',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'session'], name='rec_student_session_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['marked_at'], name='rec_marked_at_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status'], name='rec_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['class_obj', 'start_time'], name='sess_class_start_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['status', 'start_time'], name='sess_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['teacher', 'start_time'], name='sess_teacher_start_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'class_obj'], name='enr_student_class_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrolled_at'], name='enr_enrolled_at_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='academicterm',
            unique_together={('name', 'academic_year')},
        ),
        migrations.AddField(
            model_name='class',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='attendance.academicterm'),
        ),
        migrations.AddField(
            model_name='attendanceflag',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='attendance.class'),
        ),
        migrations.AddField(
            model_name='attendanceflag',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceflag',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='attendance.attendancesession'),
        ),
        migrations.AddField(
            model_name='attendanceflag',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interventionlog',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='attendance.announcement'),
        ),
        migrations.AddField(
            model_name='interventionlog',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='attendance.class'),
        ),
        migrations.AddField(
            model_name='interventionlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attendanceflag',
            index=models.Index(fields=['status', 'severity'], name='flag_status_sev_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceflag',
            index=models.Index(fields=['class_obj', 'status'], name='flag_class_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceflag',
            index=models.Index(fields=['student', 'status'], name='flag_student_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceflag',
            unique_together={('session', 'student', 'flag_type')},
        ),
        migrations.AddIndex(
            model_name='interventionlog',
            index=models.Index(fields=['student', 'sent_at'], name='iv_student_sent_idx'),
        ),
        migrations.AddIndex(
            model_name='interventionlog',
            index=models.Index(fields=['class_obj', 'outcome'], name='iv_class_outcome_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interventionlog',
            unique_together={('announcement', 'student')},
        ),
    ]
